# Use the official MySQL image as the base image
FROM mysql:latest

# Set the working directory
WORKDIR /docker-entrypoint-initdb.d

# Copy the initialization script and set the correct permissions
COPY karbanScript-v0.sql /docker-entrypoint-initdb.d/karbanScript-v0.sql
RUN chmod 444 /docker-entrypoint-initdb.d/karbanScript-v0.sql
